blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://discord.gg/jWdfVh3
    about: Please join our Discord server and request a feature in the \#suggestions channel.
