package mod.adrenix.nostalgic.tweak.factory;

import mod.adrenix.nostalgic.network.packet.tweak.ClientboundTweakEnum;
import mod.adrenix.nostalgic.network.packet.tweak.ServerboundTweakEnum;
import mod.adrenix.nostalgic.network.packet.tweak.TweakPacket;
import mod.adrenix.nostalgic.tweak.TweakEnv;
import mod.adrenix.nostalgic.tweak.container.Container;
import mod.adrenix.nostalgic.tweak.enums.EnumTweak;
import mod.adrenix.nostalgic.util.common.lang.DecodeLang;
import net.minecraft.network.chat.Component;
import org.jetbrains.annotations.Nullable;

import java.util.Locale;

public class TweakEnum<T extends Enum<T> & EnumTweak> extends TweakValue<T>
{
    /* Factories */

    /**
     * Build a new {@link TweakEnum} instance that is only available for the client. Reference the {@code see also} link
     * for more information about client tweaks.
     *
     * @param defaultEnum The tweak's default value.
     * @param container   The tweak's {@link Container}, either a {@code category} or {@code group}.
     * @param <E>         The enum class type of the default value.
     * @return A new {@link TweakEnum.Builder} instance.
     * @see TweakEnv#CLIENT
     */
    public static <E extends Enum<E> & EnumTweak> TweakEnum.Builder<E> client(E defaultEnum, Container container)
    {
        return new Builder<>(defaultEnum, TweakEnv.CLIENT, container);
    }

    /**
     * Build a new {@link TweakNumber} instance that is available for both the client and server. Reference the
     * {@code see also} link for more information about server tweaks.
     *
     * @param defaultEnum The tweak's default value.
     * @param container   The tweak's {@link Container}, either a {@code category} or {@code group}.
     * @param <E>         The enum class type of the default value.
     * @return A new {@link TweakEnum.Builder} instance.
     * @see TweakEnv#SERVER
     */
    public static <E extends Enum<E> & EnumTweak> TweakEnum.Builder<E> server(E defaultEnum, Container container)
    {
        return new Builder<>(defaultEnum, TweakEnv.SERVER, container);
    }

    /**
     * Build a new {@link TweakNumber} instance that is dynamic. Reference the {@code see also} link for more
     * information about dynamic tweaks.
     *
     * @param defaultEnum The tweak's default value.
     * @param container   The tweak's {@link Container}, either a {@code category} or {@code group}.
     * @param <E>         The enum class type of the default value.
     * @return A new {@link TweakEnum.Builder} instance.
     * @see TweakEnv#DYNAMIC
     */
    public static <E extends Enum<E> & EnumTweak> TweakEnum.Builder<E> dynamic(E defaultEnum, Container container)
    {
        return new Builder<>(defaultEnum, TweakEnv.DYNAMIC, container);
    }

    /* Constructor */

    TweakEnum(TweakEnum.Builder<T> builder)
    {
        super(builder);
    }

    /**
     * Overload method for {@link Tweak#setCacheValue(Object)} to handle enum values from an enum constants array. Type
     * information gets lost, so setting the cache throws an error. This method handles that situation.
     *
     * @param value An {@link Enum} value.
     */
    @SuppressWarnings("unchecked") // Enum values comes from an enum constants array generated by the tweak
    public void setCacheValue(Enum<?> value)
    {
        this.setCacheValue((T) value);
    }

    /**
     * Get the enumeration description key for this tweak based on the given enum value.
     *
     * @param value An enumeration value.
     * @return A lang file key.
     */
    private String getEnumKey(Enum<?> value)
    {
        return this.getLangKey() + ".enum." + value.name().toLowerCase(Locale.ROOT);
    }

    /**
     * Get an enum description that is specific to a tweak's implementation of the enum value. An example lang key for a
     * tweak enum description would be {@code gui.nostalgic_tweaks.config.mod.defaultScreen.enum.main_menu}. Where
     * {@code main_menu} is the enumeration name from some enum class. The enum value string is set to lowercase when
     * retrieving a translation value.
     *
     * @param value An enum value.
     * @return A {@link Component} enum description unique to this tweak's implementation.
     */
    public Component getEnumDescription(Enum<?> value)
    {
        return DecodeLang.findAndReplace(Component.translatable(this.getEnumKey(value)));
    }

    /**
     * Check if the given enumeration value has a custom description provided by this tweak.
     *
     * @param value An enumeration value.
     * @return Whether a custom description for the enumeration value exists.
     */
    public boolean isEnumDescribed(Enum<?> value)
    {
        return !this.getEnumDescription(value).getString().equals(this.getEnumKey(value));
    }

    @Override
    public @Nullable TweakPacket getClientboundPacket()
    {
        return new ClientboundTweakEnum(this);
    }

    @Override
    public @Nullable TweakPacket getServerboundPacket()
    {
        return new ServerboundTweakEnum(this);
    }

    /* Builder */

    public static class Builder<V extends Enum<V> & EnumTweak> extends TweakValue.Builder<V, Builder<V>>
    {
        /* Constructor */

        Builder(V defaultValue, TweakEnv env, Container container)
        {
            super(defaultValue, env, container);
        }

        /* Methods */

        @Override
        Builder<V> self()
        {
            return this;
        }

        /**
         * Finalize the building process.
         *
         * @return A new {@link TweakEnum} instance.
         */
        public TweakEnum<V> build()
        {
            return new TweakEnum<>(this);
        }
    }
}
