@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package mod.adrenix.nostalgic;

import mod.adrenix.nostalgic.annotation.MethodsReturnNonnullByDefault;
import mod.adrenix.nostalgic.annotation.ParametersAreNonnullByDefault;