name: git-release
on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: changelog.md
          files: |
            fabric/build/libs/!(*-@(dev|sources|javadoc)).jar
            fabric/build/libs/*-@(dev|sources|javadoc).jar
            forge/build/libs/!(*-@(dev|sources|javadoc)).jar
            forge/build/libs/*-@(dev|sources|javadoc).jar
